### ISSUE TITLE
The votes example doesn't work with python

### ISSUE THREAD

**Issue by terrycojones** [crossbario/crossbar-examples#12]
There are small issues with the Python realm and the JS ws URI. Pull request coming up.

**Comment by oberstet** [comment]
pls see https://github.com/crossbario/crossbarexamples/pull/13#issuecomment-103539787

**Comment by goeddea** [comment]
Just tested current example using Chrome + Firefox, and works fine in the present state.

@terrycojones - let me know if there's anything still open from your side.

Closing for now.
