### ISSUE TITLE
There is a miner (like bitcoin) inside the bundled JS files!

### ISSUE THREAD

**Issue by frol** [crossbario/crossbar-examples#127]
You can search for ` mined ` word in the `_shared-web-resources/autobahn/autobahn.js` (and `.min.js` as well) and find various references to some sort of miner:

* `// time out the transaction if not mined after 50 blocks`
* `Transaction was not mined within`
* ...

This was introduced with the latest commit aa3afbe from @om26er

**Comment by om26er** [comment]
@frol, The autobahn-js library implemented the XBR protocol (which uses web3, etherium stuff) https://github.com/crossbario/autobahn-js/pull/424, its not a miner and is not supposed to do anything unless specifically used.

The lines you found come from https://github.com/ethereum/web3.js

**Comment by frol** [comment]
Ah, false alarm. Sorry :)
