### ISSUE TITLE
Run client.py and get AssertionError

### ISSUE THREAD

**Issue by lyn5466** [crossbario/crossbar-examples#38]
Hi, 

I am able to successfully run a crossbar node. Then, I want to start a client which is not on the same machine as Django and crossbar node, and I got the AssertionError as follows:
(The `monitor.py` is the same as `client.py`)

```
ubuntu@some-ip:~/wamp_monitor$ python monitor.py 
Traceback (most recent call last):
  File "monitor.py", line 143, in <module>
    app.run(url="ws://%s:80/ws" % SERVER, debug=False, debug_wamp=False)
  File "/usr/local/lib/python2.7/dist-packages/autobahn/twisted/wamp.py", line 381, in run
    debug=debug, debug_wamp=debug_wamp, debug_app=debug_app)
  File "/usr/local/lib/python2.7/dist-packages/autobahn/twisted/wamp.py", line 134, in __init__
    assert(type(url) == six.text_type)
AssertionError
```

Any suggestion? 
Thanks

**Comment by slav0nic** [comment]
what if mark url as unicode? like 

```
app.run(url=u"ws://%s:80/ws" % SERVER, debug=False, debug_wamp=False)
```

**Comment by lyn5466** [comment]
Oh! This works! Thanks!

**Comment by dkdndes** [comment]
Hi, I did the same but now I get the following error:

python client.py 
Connected
Entering stats loop ..
Tick
Error in stats loop: 'module' object has no attribute 'phymem_usage'

> > > import psutil
> > > dir (psutil)
> > > ['AF_LINK', 'AccessDenied', 'CONN_CLOSE', 'CONN_CLOSE_WAIT', 'CONN_CLOSING', 'CONN_ESTABLISHED', 'CONN_FIN_WAIT1', 'CONN_FIN_WAIT2', 'CONN_LAST_ACK', 'CONN_LISTEN', 'CONN_NONE', 'CONN_SYN_RECV', 'CONN_SYN_SENT', 'CONN_TIME_WAIT', 'Error', 'NIC_DUPLEX_FULL', 'NIC_DUPLEX_HALF', 'NIC_DUPLEX_UNKNOWN', 'NoSuchProcess', 'Popen', 'Process', 'STATUS_DEAD', 'STATUS_DISK_SLEEP', 'STATUS_IDLE', 'STATUS_LOCKED', 'STATUS_RUNNING', 'STATUS_SLEEPING', 'STATUS_STOPPED', 'STATUS_TRACING_STOP', 'STATUS_WAITING', 'STATUS_WAKING', 'STATUS_ZOMBIE', 'TimeoutExpired', 'ZombieProcess', '_POSIX', '_PY3', '_TOTAL_PHYMEM', '_WINDOWS', '__all__', '**author**', '**builtins**', '**doc**', '**file**', '**name**', '**package**', '**path**', '**version**', '_assert_pid_not_reused', '_common', '_compat', '_last_cpu_times', '_last_cpu_times_2', '_last_per_cpu_times', '_last_per_cpu_times_2', '_pmap', '_psosx', '_psplatform', '_psposix', '_psutil_osx', '_psutil_posix', '_timer', 'boot_time', 'callable', 'collections', 'cpu_count', 'cpu_percent', 'cpu_times', 'cpu_times_percent', 'disk_io_counters', 'disk_partitions', 'disk_usage', 'errno', 'functools', 'long', 'net_connections', 'net_if_addrs', 'net_if_stats', 'net_io_counters', 'os', 'pid_exists', 'pids', 'process_iter', 'pwd', 'signal', 'subprocess', 'swap_memory', 'sys', 'test', 'time', 'users', 'version_info', 'virtual_memory', 'wait_procs']
> > > psutil.__version__
> > > '3.2.2'

I beleive you need to install a older version - is that correct?

**Comment by daninarv** [comment]
psutil.phymem_usage() was deprecated. Try with psutil.virtual_memory() instead.

**Comment by goeddea** [comment]
(ok, looking at this somewhat late...) - Not enough information to replicate. Closing as is.

@dkdndes - If the problem persists then please re-open and add more information.
