### ISSUE TITLE
Exception on start

### ISSUE THREAD

**Issue by Ninerian** [crossbario/crossbar-examples#63]
I pulled the last version from your repository, as also the autobahn-python repository. After installing both, I get the following error on startup:

```
[Controller  76141] Traceback (most recent call last):  
[Controller  76141]   File "/usr/local/lib/python2.7/site-packages/crossbar-0.13.0-py2.7.egg/crossbar/controller/node.py", line 497, in start
[Controller  76141]     yield self._startup(self._config)
[Controller  76141] TypeError: __init__() got an unexpected keyword argument 'debug'
```

I tried to uninstall and reinstall the libraries, but this didn't help. The error occurs when I try to run a example from the repo.

Do you have any guess, how I can fix it?

**Comment by oberstet** [comment]
dont run trunk - it might be broken
