### ISSUE TITLE
Sliders demo on Android

### ISSUE THREAD

**Issue by psyc0** [crossbario/crossbar-examples#78]
problems when trying the slider-demo on android:
symptoms: slider goes to 100% on first press, in some cases I was able to point the slider(only master volume) to specific values but mostly the behaviour was unpredictable or nothing happened.
As im looking to implement this on mobile-devices I got a little concerned.
running on:
android 6.0.1
chrome 53.0.2785

**Comment by goeddea** [comment]
The demo is old and uses sliders from jqueryUI from years ago. These were not designed with mobile use in mind, so the problems stem from that. 
There's no reason to worry about AutobahnJS  - this works fine in modern mobile browsers.
