### ISSUE TITLE
Bad url in website

### ISSUE THREAD

**Issue by andreagilardoni** [crossbario/crossbar-examples#84]
There is a bad url in this page: http://crossbar.io/docs/Authorization/#dynamic-authorization at the line: "For fully-worked examples, see crossbarexample/authorization." and the link leads here: "https://github.com/crossbario/crossbar-examples/tree/master/authorization/dynamic>" instead of here: "https://github.com/crossbario/crossbar-examples/tree/master/authorization/dynamic". It is a typo.

**Comment by goeddea** [comment]
@alcheagle - Thanks for filing this!
