### ISSUE TITLE
Excluding subscribers demo does not work

### ISSUE THREAD

**Issue by koxu1996** [crossbario/crossbar-examples#93]
I was trying to use eligible_authid in this way:

```
$session->publish('com.user.' . $details->caller_authid . '.update_points', [$user->points], null, ["eligible_authid" => [$details->caller_authid]]);
```

but I was receiving `ProtocolError: invalid type <type 'unicode'> for value in 'eligible_authid' option in PUBLISH`. I did not know this is Crossbar or Thruway issue so I decided to try example. But when I execute `crossbar start` then I am getting: 

```
invalid attribute value 'universal' for attribute 'type' in transport item
```

**Comment by oberstet** [comment]
Can you try with the latest Crossbar.io release? https://pypi.python.org/pypi/crossbar/17.3.1

Because this extensive example works for me (just checked again): https://github.com/crossbario/crossbar-examples/tree/master/exclude_subscribers

**Comment by koxu1996** [comment]
I thought I have latest version of crossbar, but I was wrong. Executing `sudo apt-get install --upgrade crossbar` is outputting:
```
crossbar is already the newest version (0.13.2-xenial)
```
I wonder why Ubuntu package is not up to date?

**Comment by oberstet** [comment]
> I wonder why Ubuntu package is not up to date?

Sorry, no time yet. But we will move to snaps anyway and not provide debs anymore.

For now, there are 2 supported ways that do work:

1. https://hub.docker.com/r/crossbario/crossbar/
2. create a dedicated Python virtualenv and pip install into that

**Comment by koxu1996** [comment]
I installed latest crossbar with pip and example is working fine.
