### ISSUE TITLE
Video control demo does not work

### ISSUE THREAD

**Issue by om26er** [crossbario/crossbar-examples#98]
The video control [demo](https://demo.crossbar.io/videocontrol/), does not work. The video never loads. If I open the [url](https://s3-eu-west-1.amazonaws.com/crossbar.io/videocontrol_data/trailer.ogv) directly, the error is "NoSuchKey"

**Comment by goeddea** [comment]
Thanks for reminding me. This should be the last fallout from our removal of the S3 bucket hosting autobahn.js builts. 

Note to myself: The reason we were hosting the video + post image was that we wanted to serve this via HTTPS to avoid a mixed content warning in the browser.
